### PR TITLE
Warn browsers < IE 10

### PR DESCRIPTION
**Pull request by eeeschwartz**

### CODE REVIEW

**Comment by migurski** [comment]
Is the site non-functional on older browsers? If it still works, I’d be inclined to not offer this warning to users.

**Comment by eeeschwartz** [comment]
@migurski the site is essentially a d3 map so non-functional for IE 8 and lower. We have an issue to fix IE 9 (#66) but it's down the priority list for the moment.

**Comment by migurski** [comment]
It may be helpful to rephrase the warning in that case. Right now “better experience this site” doesn’t convey that the site won’t be experienced at all on an older browser.

**Comment by eeeschwartz** [comment]
@migurski good call.

**Pull request merged**
